// All valid HTML roles
// Go to https://www.w3.org/TR/html-aria/#docconformance
// and paste the code below in the console to get all roles
// [...document.querySelectorAll('td code')].filter(n => n.innerText.startsWith('role=')).map(n => n.innerText.replace('role=', '')).filter((r,i,s) => s.indexOf(r) === i)
export const Roles = {
  link: "link",
  article: "article",
  complementary: "complementary",
  document: "document",
  button: "button",
  listbox: "listbox",
  definition: "definition",
  term: "term",
  group: "group",
  dialog: "dialog",
  figure: "figure",
  contentinfo: "contentinfo",
  form: "form",
  heading: "heading",
  banner: "banner",
  separator: "separator",
  img: "img",
  checkbox: "checkbox",
  textbox: "textbox",
  spinbutton: "spinbutton",
  radio: "radio",
  slider: "slider",
  searchbox: "searchbox",
  combobox: "combobox",
  listitem: "listitem",
  main: "main",
  math: "math",
  list: "list",
  navigation: "navigation",
  option: "option",
  status: "status",
  progressbar: "progressbar",
  region: "region",
  table: "table",
  rowgroup: "rowgroup",
  cell: "cell",
  gridcell: "gridcell",
  grid: "grid",
  columnheader: "columnheader",
  row: "row",
  treegrid: "treegrid",
} as const
